x86/asm: Fix SETZ size enqcmds() build failure
ANBZ: #22

commit d81ff5fe14a950f53e2833cfa196e7bb3fd5d4e3 upstream.

When building under GCC 4.9 and 5.5:

  arch/x86/include/asm/special_insns.h: Assembler messages:
  arch/x86/include/asm/special_insns.h:286: Error: operand size mismatch for `setz'

Change the type to "bool" for condition code arguments, as documented.

Intel-SIG: commit d81ff5fe14a9 x86/asm: Fix SETZ size enqcmds() build failure.
Incremental backporting patches for DSA/IAX on Intel Xeon platform.

Fixes: 7f5933f81bd8 ("x86/asm: Add an enqcmds() wrapper for the ENQCMDS instruction")
Co-developed-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Kees Cook <keescook@chromium.org>
Signed-off-by: Borislav Petkov <bp@suse.de>
Link: https://lkml.kernel.org/r/20210910223332.3224851-1-keescook@chromium.org
[ Xiaochen Shen: amend commit log ]
Signed-off-by: Xiaochen Shen <xiaochen.shen@intel.com>
Reviewed-by: Zelin Deng <zelin.deng@linux.alibaba.com>