anolis: psi: fix compile error when cgroup disabled
ANBZ: #3341

Fix the following compiling errors when disable cgroup:

In file included from fs/io-wq.c:24:
fs/../kernel/sched/sched.h:2898:22: error: array type has incomplete element type ‘struct cftype’
 2898 | extern struct cftype cgroup_v1_psi_files[];
      |                      ^~~~~~~~~~~~~~~~~~~

Fixes: 6988de8b870cd ("ck: psi: Support PSI under cgroup v1")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Reviewed-by: Jingbo Xu <jefflexu@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/968