anolis: Revert "selftest: kvm: Add amx selftest"
ANBZ: #4307

This reverts commit 62089fe62b06d2335fb47c47b2b2477788bd15c4.

The origin commit leads compiler warnings and errors due to some omitted patches. Such as:
 - x86_64/amx_test.c:275:8: error: ‘MSR_IA32_XFD’ undeclared (first use in this function); did you mean ‘MSR_IA32_XSS’?
 - x86_64/amx_test.c:358:2: warning: implicit declaration of function ‘vm_install_exception_handler’; did you mean ‘vm_handle_exception’? [-Wimplicit-function-declaration]

We do not concern the kvm selftests about amx now. So just revert it.

Signed-off-by: Guanjun <guanjun@linux.alibaba.com>