anolis: mm/damon: add the limitation of CONFIG_DAMON_DBGFS to damon_numa_fault
ANBZ: #2280

Compilation failed when CONFIG_DAMON_DBGFS was turned off, like this:

mm/damon/core.c:1110: undefined reference to `dbgfs_nr_ctxs'
mm/damon/core.c:1110: undefined reference to `dbgfs_ctxs'

'dbgfs_nr_ctxs' and 'dbgfs_ctxs' is defined in dbgfs.c, it used in core.c,
so compilation failed when CONFIG_DAMON_DBGFS was turned off.

These two fields are mainly used by the damon_numa_fault interface, so add
the limitation of CONFIG_DAMON_DBGFS to it.

Signed-off-by: Gou Hao <gouhao@uniontech.com>