anolis: mm/damon: move numa_stat_enabled_key to core.c
ANBZ: #2280

Compilation failed when CONFIG_DAMON_DBGFS was turned off, like this:

mm/damon/core.o: undefined reference to `numa_stat_enabled_key'
mm/damon/vaddr.o: undefined reference to `numa_stat_enabled_key'

At present, 'numa_stat_enabled_key' is defined in dbgfs.c, it used
in many files(core.c, dbgfs.c, vaddr.c), so compilation failed when
CONFIG_DAMON_DBGFS was turned off.

So put the definition of 'numa_stat_enabled_key' in core.c is
appropriate.

Signed-off-by: Gou Hao <gouhao@uniontech.com>