anolis: sw64: add missing global __constant_c_memset
ANBZ: #4688

This patch fixes undefined reference to __constant_c_memset if
CONFIG_DEEP_MEMSET=y and CONFIG_VGA_CONSOLE=y.

Signed-off-by: He Sheng <hesheng@wxiat.com>
Reviewed-by: Cui Wei <cuiwei@wxiat.com>
Signed-off-by: Gu Zitao <guzitao@wxiat.com>