tcp: Add a stub for sk_defer_free_flush()
ANBZ: #4327

commit 48cec899e357cfb92d022a9c0df6bbe72a7f6951 upstream.

When compiling the kernel with CONFIG_INET disabled, the
sk_defer_free_flush() should be defined as a nop.

This resolves the following compilation error:
  ld: net/core/sock.o: in function `sk_defer_free_flush':
  ./include/net/tcp.h:1378: undefined reference to `__sk_defer_free_flush'

Signed-off-by: leoliu-oc <leoliu-oc@zhaoxin.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/1339