anolis: spec: add openssl dependency
ANBZ: #6189

The openssl dependency was removed by follow commit:
637213890da8("anolis: spec: remove sign modules related codes")

But it is still necessary by scripts/sign-file.c:25 even though ANCK do not
need to sign modules.
So it triggers such error:
> scripts/sign-file.c:25:10: fatal error: openssl/opensslv.h: No such file or directory
>  #include <openssl/opensslv.h>
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated

So add this dependency back to let kernel build sucess.

Fixes: 637213890da8("anolis: spec: remove sign modules related codes")
Signed-off-by: Qiao Ma <mqaio@linux.alibaba.com>