spdxcheck.py: Fix a type error
ANBZ: #5555

commit 28c9f3f9a01d954d8357bdb68fbe36255997bf14 upstream.

remove unused variable "col", otherwise there will be a type error as below:

typeerror: not all arguments converted during string formatting

Signed-off-by: Ding Xiang <dingxiang@cmss.chinamobile.com>
Link: https://lore.kernel.org/r/20220114024058.74536-1-dingxiang@cmss.chinamobile.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: zhujun2 <zhujun2_yewu@cmss.chinamobile.com>
Reviewed-by: Peng Wang <rocking@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/1755