anolis: io_uring: fix compile error when cgroup disabled
ANBZ: #3342

Fix the following compiling errors when disable cgroup:

fs/io_uring.c: In function ‘io_sq_attach_cpu_cgroup’:
fs/io_uring.c:6865:14: error: implicit declaration of function ‘task_get_css’ [-Werror=implicit-function-declaration]
 6865 |  css_owner = task_get_css(current, cpuacct_cgrp_id);
      |              ^~~~~~~~~~~~
fs/io_uring.c:6865:36: error: ‘cpuacct_cgrp_id’ undeclared (first use in this function)
 6865 |  css_owner = task_get_css(current, cpuacct_cgrp_id);
      |                                    ^~~~~~~~~~~~~~~
fs/io_uring.c:6865:36: note: each undeclared identifier is reported only once for each function it appears in
fs/io_uring.c:6868:15: error: dereferencing pointer to incomplete type ‘struct cgroup_subsys_state’
 6868 |  if (css_owner->cgroup == css_sq->cgroup)
      |               ^~
fs/io_uring.c:6878:8: error: implicit declaration of function ‘cgroup_path’; did you mean ‘cgroup_psi’? [-Werror=implicit-function-declaration]
 6878 |  ret = cgroup_path(css_owner->cgroup, buf + size, 4096 - size);
      |        ^~~~~~~~~~~
      |        cgroup_psi

Fixes: 40af84221636 ("alinux: io_uring: allow sqthread to inherit cpuacct from its creator")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>