anolis: swiotlb: export swiotlb_max_mapping_size()
OpenAnolis Bug Tracker: 0000546

ERROR: "swiotlb_max_mapping_size" [drivers/virtio/virtio_ring.ko]
undefined!

The compiler complains above in case of CONFIG_VIRTIO=m, export it.

Fixes: ce91e1727eea ("alinux: virtio_ring: Distinguish max mapping size between swiotlb and direct dma")
Reviewed-by: Shile Zhang <shile.zhang@linux.alibaba.com>
Signed-off-by: Xunlei Pang <xlpang@linux.alibaba.com>