openeuler: nmi_watchdog: add asm/nmi.h for ARM64
commit 737c7d1988dd5266303b3c2b990f0721ed963ddf openEuler-1.0.

When I compile the kernel with CONFIG_SDEI_WATCHDOG chosen and without
CONFIG_HARDLOCKUP_DETECTOR, I got the following error.
./include/linux/nmi.h: In function 'touch_nmi_watchdog':
./include/linux/nmi.h:141:2: error: implicit declaration of function 'arch_touch_nmi_watchdog' [-Werror=implicit-function-declaration]
  arch_touch_nmi_watchdog();
  ^~~~~~~~~~~~~~~~~~~~~~~

It is because CONFIG_SDEI_WATCHDOG selects HAVE_NMI_WATCHDOG, but we
didn't provide arch_touch_nmi_watchdog for ARM64 in 'asm/nmi.h'. This
patch implements arch_touch_nmi_watchdog() for ARM64 when
CONFIG_HARDLOCKUP_DETECTOR is not chosen.

Signed-off-by: Xiongfeng Wang <wangxiongfeng2@huawei.com>
Reviewed-by: Yang Yingliang <yangyingliang@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>
Signed-off-by: Xin Hao <haoxing990@gmail.com>
Reviewed-by: Baolin Wang <baolin.wang@openanolis.org>