iommu/vt-d: Fix compile error [-Werror=implicit-function-declaration]
ANBZ: #1946

commit e1ed66ac300373a8d7e8d95fd86ca522f36602d9 upstream.

trace_qi_submit() could be used when interrupt remapping is supported,
but DMA remapping is not. In this case, the following compile error
occurs.

../drivers/iommu/intel/dmar.c: In function 'qi_submit_sync':
../drivers/iommu/intel/dmar.c:1311:3: error: implicit declaration of function 'trace_qi_submit';
  did you mean 'ftrace_nmi_exit'? [-Werror=implicit-function-declaration]
   trace_qi_submit(iommu, desc[i].qw0, desc[i].qw1,
   ^~~~~~~~~~~~~~~
   ftrace_nmi_exit

Intel-SIG: commit e1ed66ac3003 iommu/vt-d: Fix compile error [-Werror=implicit-function-declaration].

Fixes: f2dd871799ba5 ("iommu/vt-d: Add qi_submit trace event")
Reported-by: kernel test robot <lkp@intel.com>
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Lu Baolu <baolu.lu@linux.intel.com>
Link: https://lore.kernel.org/r/20210130151907.3929148-1-baolu.lu@linux.intel.com
Signed-off-by: Joerg Roedel <jroedel@suse.de>
[ Fengqian Gao: amend commit log ]
Signed-off-by: Fengqian Gao <fengqian.gao@intel.com>
Signed-off-by: Aubrey Li <aubrey.li@linux.intel.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/659
Reviewed-by: Artie Ding <artie.ding@linux.alibaba.com>