anolis: spec: avoid override system %rpmversion definition
ANBZ: #7810

It will report such error on Anolis 23 baseos:
> # yum-builddep -y kernel.spec
> Last metadata expiration check: 0:21:45 ago on Thu Dec 28 09:02:26 2023.
> RPM: error: kernel.spec: line 11: Macro %rpmversion is a built-in (%define)
> Failed to open: 'kernel.spec', not a valid spec file: can't parse specfile
>
> Error: Some packages could not be found.

The root cause is that higher version rpmbuild has built-in the variable
%rpmversion, which is confilict with kernel.spec.
So replace variable %rpmversion to %kernelversion.

Signed-off-by: Qiao Ma <mqaio@linux.alibaba.com>
Reviewed-by: Guixin Liu <kanie@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/2558