anolis: psi: fix compile error when cgroup disabled
ANBZ: #3342

Fix the following compiling errors when disable cgroup:

In file included from kernel/livepatch/transition.c:27:
kernel/livepatch/../sched/sched.h:2503:22: error: array type has incomplete element type ‘struct cftype’
 2503 | extern struct cftype cgroup_v1_psi_files[];

Fixes: 1f49a7385032 ("alinux: psi: Support PSI under cgroup v1")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Reviewed-by: Jingbo Xu <jefflexu@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/972