kunit: testing kunit: Bug fix in test_run_timeout function
OpenAnolis Bug Tracker: 0000567

commit 70efb58bbbc2 upstream

Assert in test_run_timeout was not updated with the build_dir argument
and caused the following error:
AssertionError: Expected call: run_kernel(timeout=3453)
Actual call: run_kernel(build_dir=None, timeout=3453)

Needed to update kunit_tool_test to reflect this fix
https://lkml.org/lkml/2019/9/6/351

Signed-off-by: Heidi Fahim <heidifahim@google.com>
Reviewed-by: SeongJae Park <sjpark@amazon.de>
Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
Tested-by: Brendan Higgins <brendanhiggins@google.com>
Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
Upstream-v5.5-SHA1: 70efb58bbbc28f0cbd4060c9aa581d79201c8b1a
Signed-off-by: Jay Chen <jkchen@linux.alibaba.com>
Reviewed-by: zou cao <zoucao@linux.alibaba.com>
Signed-off-by: Baolin Wang <baolin.wang@linux.alibaba.com>