anolis: perf mem: fix build error in evlist__check_mem_load_aux()
ANBZ: #9661

evlist__check_mem_load_aux() is introduced, but we missed that a previous patch
8117e613a1cb ("libperf: Move 'leader' from tools/perf to
perf_evsel::leader") already remove 'leader' in struct evsel. So cause a
compiler error.

tools/perf/util/evlist.c:1998:17: error: ‘struct evsel’ has no member named ‘leader’
 1998 |   leader = evsel->leader;
      |                 ^~
tools/perf/util/evlist.c:2004:8: error: ‘struct evsel’ has no member named ‘leader’
 2004 |     pos->leader = pos;
      |        ^~
error: command 'gcc' failed with exit status 1

So, we fix this based on 8117e613a1cb ("libperf: Move 'leader' from tools/perf to
perf_evsel::leader").

Fixes: 3796cc24d1f5 ("perf mem: Disable 'mem-loads-aux' group before reporting")
Signed-off-by: Kun(llfl) <llfl@linux.alibaba.com>
Reviewed-by: Artie Ding <artie.ding@linux.alibaba.com>
Reviewed-by: Zelin Deng <zelin.deng@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/3622