anolis: io_uring: fix compile error when cgroup disabled
ANBZ: #3341

Fix the following compiling errors when disable cgroup:

fs/io_uring.c: In function ‘io_sq_attach_cpu_cgroup’:
fs/io_uring.c:7094:14: error: implicit declaration of function ‘task_get_css’ [-Werror=implicit-function-declaration]
 7094 |  css_owner = task_get_css(current, cpuacct_cgrp_id);
      |              ^~~~~~~~~~~~
fs/io_uring.c:7094:36: error: ‘cpuacct_cgrp_id’ undeclared (first use in this function)
 7094 |  css_owner = task_get_css(current, cpuacct_cgrp_id);
      |                                    ^~~~~~~~~~~~~~~
fs/io_uring.c:7094:36: note: each undeclared identifier is reported only once for each function it appears in
fs/io_uring.c:7096:15: error: dereferencing pointer to incomplete type ‘struct cgroup_subsys_state’
 7096 |  if (css_owner->cgroup == css_sq->cgroup)
      |               ^~
fs/io_uring.c:7106:8: error: implicit declaration of function ‘cgroup_path’; did you mean ‘cgroup_psi’? [-Werror=implicit-function-declaration]
 7106 |  ret = cgroup_path(css_owner->cgroup, buf + size, 4096 - size);
      |        ^~~~~~~~~~~
      |        cgroup_psi

Fixes: cae05f877e943 ("anolis: io_uring: allow sqthread to inherit cpuacct from its creator")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Reviewed-by: Jingbo Xu <jefflexu@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/968