anolis: Fix compilation error with rich container
ANBZ: #4631

The rich container boot cmdline parameter handle rich_container_enable()
tries to set __sched_schedstats as well, but that variable won't exist
if CONFIG_SCHEDSTATS is not set. This causes a compilation error as:

```
kernel/pid_namespace.o: In function `rich_container_enable':
pid_namespace.c:(.init.text+0x13): undefined reference to `__sched_schedstats'
make: *** [Makefile:1188: vmlinux] Error 1
```

Fixes: e777fc6b981e ("anolis: Add a boot command line for rich container")
Signed-off-by: Liu Song <liu.song13@zte.com.cn>